version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: serdron/api_yamdb
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env 

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./certbot/conf:/etc/letsencrypt
      - ./public:/var/www/certbot
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./public:/var/www/certbot

volumes:
  static_value:
  media_value:
  data:
 
